##############################################################################################
# This role creates the value file for notary
##############################################################################################

# Create deployment file for CENM notary service db
- name: "Create db for notary"
  include_role:
    name: helm_component
  vars:
    component_name: "{{ org.services.notary.name | lower }}db"
    component_ns: "{{ org.name | lower }}-ent"
    type: "notarydb"
    values_dir: "{{ playbook_dir }}/../../../{{ org.gitops.release_dir }}"
    name: "{{ org.name | lower }}"
    charts_dir: "{{ org.gitops.chart_source }}"
    git_url: "{{ org.gitops.git_ssh }}"
    git_branch: "{{ org.gitops.branch }}"
    node_name: "{{ org.services.notary.name }}"
    image_pull_secret: "regcred"
    storageclass: "awsstorageclass"
    container_name: "{{ network.docker.url }}/h2:2018"
    ports_tcp: "{{ org.services.notary.dbtcp }}"
    ports_web: "{{ org.services.notary.dbweb }}"
    helm_lint: "true"
   
    
# # Push the notary deployment files to repository
# - name: "Push the created deployment files to repository"
#   include_role: 
#     name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
#   vars:
#     GIT_DIR: "{{ playbook_dir }}/../../../"
#     GIT_REPO: "{{ org.gitops.git_push_url }}"
#     GIT_USERNAME: "{{ org.gitops.username }}"
#     GIT_EMAIL: "{{ org.gitops.email }}"
#     GIT_PASSWORD: "{{ org.gitops.password }}"
#     GIT_BRANCH: "{{ org.gitops.branch }}"
#     GIT_RESET_PATH: "platforms/corda-ent/configuration"
#     msg: "[ci skip] Pushing deployment files for notary service"
