apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrierkdregistration
  namespace: carrierkd-ent
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrierkdregistration
  chart:
    git: https://github.com/deepakkumardbd/blockchain-automation-framework.git
    ref: dev
    path: platforms/r3-corda-ent/charts/node-initial-registration
  values:
    nodeName: carrierkd-registration
    metadata:
      namespace: carrierkd-ent
      labels: {}
    image:
      initContainerName: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
      nodeContainerName: adopblockchaincloud0502.azurecr.io/corda/enterprise-node:4.4
      imagepullsecret: regcred
      pullPolicy: Always
    truststorePassword: password
    keystorePassword: password
    acceptLicence: true
    networkServices:
      doormanURL: https://idmankd.rc.dev2.aws.blockchaincloudpoc-develop.com:8443
      networkMapURL: https://networkmapkd.rc.dev2.aws.blockchaincloudpoc-develop.com:8443 
      idmanDomain: "idmankd.rc.dev2.aws.blockchaincloudpoc-develop.com"
      networkMapDomain: "networkmapkd.rc.dev2.aws.blockchaincloudpoc-develop.com"
      idmanName: "idmankd"
      networkmapName: "networkmapkd"
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      floatVaultAddress: ""
      authpathFloat: ""
      role: vault-role
      authpath: cordaentcarrierkd
      serviceaccountname: vault-auth
      certsecretprefix: secret/carrierkd/carrierkd
      nodePath: carrierkd
      retries: 30
      retryInterval: 30
    firewall:
      enabled: False
    nodeConf:
      ambassador:
        external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
        p2pPort: 15030
        p2pAddress: carrierkd.rc.dev2.aws.blockchaincloudpoc-develop.com:15030
      legalName: "O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB"
      emailAddress: dev-node@baf.com
      crlCheckSoftFail: true
      tlsCertCrlDistPoint: ""
      tlsCertCrlIssuer: "CN=Corda TLS CRL Authority,OU=Corda UAT,O=R3 HoldCo LLC,L=New York,C=US"
      devMode: false
      volume:
        baseDir: /opt/corda
      jarPath: bin
      configPath: etc
      cordaJar:
        memorySize: 1524
        unit: M
      pod:
        resources:
          limits: 1524M
          requests: 1524M
    service:
      p2pPort: 10002
      p2pAddress: carrierkd.carrierkd-ent
      messagingServerPort: 10002
      ssh:
        enabled: true
        sshdPort: 2222
      rpc:
        port: 30000
        adminPort: 30009
        users:
        - name: carrierkd
          password: carrierkdP
          permissions: ALL
    dataSourceProperties:
      dataSource:
        user: carrierkd-db-user
        password: carrierkd-db-password
        url: "jdbc:h2:tcp://carrierkddb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        dbUrl: "carrierkddb"
        dbPort: 9101
      monitoring:
        enabled: true
        port: 8090
      allowDevCorDapps:
        enabled: true
      retries: 20
      retryInterval: 15
    sleepTimeAfterError: 120
    sleepTime: 0
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold:  15
