apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cenmkdpkigenerator
  namespace: cenmkd-ent
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: cenmkdpkigenerator
  chart:
    git: git@github.com:deepakkumardbd/blockchain-automation-framework.git
    ref: corda-checks-test
    path: platforms/corda-ent/charts/generate-pki
  values:
    nodeName: cenmkd-pki
    cenmServices:
      signerName: signerkd
      idmanName: idmankd
      networkmapName: networkmapkd
      notaryName: notarykd
    replicas: 1
    metadata:
      namespace: cenmkd-ent
    dockerImagePki:
      name: corda/enterprise-pkitool
      tag: 1.2-zulu-openjdk8u242
      pullPolicy: Always
    image:
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
    volume:
      baseDir: /opt/corda
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:8081
      role: vault-role
      authpath: cordaentcenmkd
      serviceaccountname: vault-auth
      certsecretprefix: secret/cenmkd
    healthcheck:
      readinesscheckinterval: 20
      readinessthreshold: 20
    serviceSsh:
      type: ClusterIP
      port: 2222
      targetPort: 2222
      nodePort:
    shell:
      user: signer
      password: signerP
    idmanPublicIP: idmankd.rc.dev.aws.blockchaincloudpoc-develop.com
    idmanPort: 8443
    serviceLocations:
      identityManager:
        host: idmankd.cenmkd-ent
        port: 5052
      networkMap:
        host: networkmapkd.cenmkd-ent
        port: 5050
      revocation:
        port: 5053
    signers:
      CSR:
        schedule:
          interval: 1m 
      CRL:
        schedule:
          interval: 1d
      NetworkMap:
        schedule:
          interval: 1m
      NetworkParameters:
        schedule:
          interval: 1m
    cordaJarMx: 1
    healthCheckNodePort: 0
    jarPath: bin
    configPath: etc
    pki:
      certificates:
        tlscrlsigner:
          subject: "CN=Test TLS Signer Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
          crl:
            issuer: "CN=Corda TLS CRL Authority,OU=Corda UAT,O=R3 HoldCo LLC,L=New York,C=US"
        cordarootca:
          subject: "CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB"
        subordinateca:
          subject: "CN=Test Subordinate CA Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
        identitymanagerca:
          subject: "CN=Test Identity Manager Service Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
        networkmap:
          subject: "CN=Test Network Map Service Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
