apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cenmkdnotary-initial-registration
  namespace: cenmkd-ent
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: cenmkdnotary-initial-registration
  chart:
    git: git@github.com:deepakkumardbd/blockchain-automation-framework.git
    ref: corda-checks-test
    path: platforms/corda-ent/charts/notary-initial-registration
  values:
    nodeName: notarykd-initial-registration
    nodePath: notarykd
    metadata:
      namespace: cenmkd-ent
    image:
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagepullsecret: regcred
    dockerImage:
      name: corda/notary
      tag: 1.2-zulu-openjdk8u242
      pullPolicy: Always
      imagePullSecret: regcred
    acceptLicense: YES
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:8081
      certsecretprefix: secret/cenmkd
      serviceaccountname: vault-auth
      role: vault-role
      authpath: cordaentcenmkd
    volume:
      baseDir: /opt/corda
    devMode: false
    ambassador_p2pPort: 15034
    p2pPort: 10002
    rpcSettingsAddress: "0.0.0.0"
    rpcSettingsAddressPort: 10003
    rpcSettingsAdminAddress: "localhost"
    rpcSettingsAdminAddressPort: 10770
    rpcSettingsStandAloneBroker: false
    rpcSettingsUseSsl: false
    networkServices:
      doormanURL: http://idmankd.cenmkd-ent:10000
      networkMapURL: http://networkmapkd.cenmkd-ent:10000
    notary:
      validating: True
    legalName: O=Notary,OU=Notary2,L=London,C=GB
    emailAddress: dev@baf.com
    notaryPublicIP: notarykd.rc.dev.aws.blockchaincloudpoc-develop.com
    rpcUsers:
      username: notary
      password: notaryP
    healthCheckNodePort: 0
    jarPath: bin
    bashDebug: false
    configPath: etc
    sleepTimeAfterError: 120
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
