apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: notarydb
  namespace: supplychain-ent
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: notarydb
  chart:
    git: ssh://git@github.com/<username>/blockchain-automation-framework.git
    ref: develop
    path: platforms/corda-ent/charts/h2
  values:
    nodeName: notary
    metadata:
      namespace: supplychain-ent
    replicaCount: 1
    image:
      conatinerName: index.docker.io/hyperledgerlabs/h2:2018
      imagePullSecret: regcred
    resources:
      limits: 512Mi
      requests: 512Mi
    storage:
      name: awsstorageclass
      memory: 512Mi
    service:
      type: NodePort
      tcp:
        port: 9101
        targetPort: 1521
      web:
        targetPort: 81
        port: 8080
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}
